### ISSUE TITLE
Sametimes cannot find a tree in Error Log

### ISSUE THREAD

**Issue by apodhrad** [eclipse/reddeer#1435]
The following code

```
List<LogMessage> errors = new ErrorLogView().getErrorMessages();
```

sometimes causes

```
org.jboss.reddeer.core.exception.CoreLayerException: No matching widget found with Matcher matching when all matchers match: [Matcher matching widget with the same type as or type extending class org.eclipse.swt.widgets.Tree]
class org.eclipse.swt.widgets.Shell

    at org.jboss.reddeer.common.wait.AbstractWait.timeoutExceeded(AbstractWait.java:173)
    at org.jboss.reddeer.common.wait.AbstractWait.wait(AbstractWait.java:126)
    at org.jboss.reddeer.common.wait.AbstractWait.<init>(AbstractWait.java:91)
    at org.jboss.reddeer.common.wait.AbstractWait.<init>(AbstractWait.java:61)
    at org.jboss.reddeer.common.wait.AbstractWait.<init>(AbstractWait.java:46)
    at org.jboss.reddeer.common.wait.WaitUntil.<init>(WaitUntil.java:37)
    at org.jboss.reddeer.core.lookup.WidgetLookup.activeWidget(WidgetLookup.java:77)
    at org.jboss.reddeer.swt.widgets.AbstractWidget.<init>(AbstractWidget.java:31)
    at org.jboss.reddeer.swt.impl.tree.AbstractTree.<init>(AbstractTree.java:25)
    at org.jboss.reddeer.swt.impl.tree.DefaultTree.<init>(DefaultTree.java:67)
    at org.jboss.reddeer.swt.impl.tree.DefaultTree.<init>(DefaultTree.java:27)
    at org.jboss.reddeer.swt.impl.tree.DefaultTree.<init>(DefaultTree.java:18)
    at org.jboss.tools.common.reddeer.view.ErrorLogView.getErrorMessages(ErrorLogView.java:50)
```

![org jboss tools fuse ui bot test sapcomponenttest testsapidocdestination](https://cloud.githubusercontent.com/assets/2270674/17393795/2af93656-5a26-11e6-8a61-c72b706f0813.png)

**Comment by apodhrad** [comment]
I cannot reproduce it anymore.
