### ISSUE TITLE
ExceptionInInitializerError during loaging of properties

### ISSUE THREAD

**Issue by luvalach** [eclipse/reddeer#1740]
I am getting a ExceptionInInitializerError exception probably because of infinite loop between **RedDeerProperties** and **ExecutionSetting**. It isn't so obvious because original error are wrapped in ExceptionInInitializerError and suppressed.

Stack trace:
```
java.lang.ExceptionInInitializerError: null
    at org.eclipse.reddeer.common.context.ExecutionSetting.getInstance(ExecutionSetting.java:38)
    at org.eclipse.reddeer.common.logging.Logger.print(Logger.java:261)
    at org.eclipse.reddeer.common.logging.Logger.info(Logger.java:170)
    at org.eclipse.reddeer.common.userprofile.UserProfile.<init>(UserProfile.java:35)
    at org.eclipse.reddeer.common.userprofile.UserProfile.getInstance(UserProfile.java:64)
    at org.eclipse.reddeer.common.properties.RedDeerProperties.getValueInternal(RedDeerProperties.java:227)
    at org.eclipse.reddeer.common.properties.RedDeerProperties.<init>(RedDeerProperties.java:70)
    at org.eclipse.reddeer.common.properties.RedDeerProperties.<clinit>(RedDeerProperties.java:26)
    at org.eclipse.reddeer.common.wait.TimePeriod.<clinit>(TimePeriod.java:46)
    at org.eclipse.reddeer.core.lookup.ShellLookup.getActiveShell(ShellLookup.java:67)
    at org.eclipse.reddeer.core.lookup.MenuLookup.getActiveShellTopMenuItems(MenuLookup.java:119)
    at org.eclipse.reddeer.swt.impl.menu.ShellMenu.<init>(ShellMenu.java:48)
    at org.eclipse.reddeer.swt.impl.menu.ShellMenu.<init>(ShellMenu.java:37)
    at com.jboss.jbds.byoe.test.UpdateSiteTest.testInstallFromUpdateSite(UpdateSiteTest.java:51)
```

**Comment by rawagner** [comment]
fix is here https://github.com/eclipse/reddeer/pull/1757
