### ISSUE TITLE
Find out why is ActiveShellExistsTest.testNoActiveShellExists failing on windows 10

### ISSUE THREAD

**Issue by odockal** [eclipse/reddeer#1744]
org.eclipse.reddeer.core.test.condition.ActiveShellExistsTest.testNoActiveShellExists

Stacktrace

java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at org.junit.Assert.assertFalse(Assert.java:64)
	at org.junit.Assert.assertFalse(Assert.java:74)
	at org.eclipse.reddeer.core.test.condition.ActiveShellExistsTest.testNoActiveShellExists(ActiveShellExistsTest.java:48)
Standard Output

07:17:29.497 DEBUG [WorkbenchTestable][AbstractWait] Waiting until shell matching Matcher matching when all matchers match: [Matcher matching widget which text matches: "Test shell"] is available....
07:17:29.497 DEBUG [WorkbenchTestable][AbstractWait] Waiting until shell matching Matcher matching when all matchers match: [Matcher matching widget which text matches: "Test shell"] is available. finished successfully
07:17:29.497 DEBUG [WorkbenchTestable][AbstractShell] Set focus to Shell Test shell
07:17:29.497 DEBUG [WorkbenchTestable][AbstractWait] Waiting until shell is active...
07:17:29.497 DEBUG [WorkbenchTestable][AbstractWait] Waiting until shell is active finished successfully
07:17:29.497 DEBUG [WorkbenchTestable][AbstractShell] Set focus to Shell Test shell
07:17:29.497 DEBUG [WorkbenchTestable][AbstractWait] Waiting until shell is active...
07:17:29.497 DEBUG [WorkbenchTestable][AbstractWait] Waiting until shell is active finished successfully
07:17:29.497 INFO [WorkbenchTestable][AbstractShell] Close shell Test shell
07:17:29.497 INFO [WorkbenchTestable][ShellHandler] Closing shell 'Test shell'
07:17:29.513 DEBUG [WorkbenchTestable][AbstractWait] Waiting while shell is available...
07:17:29.528 DEBUG [WorkbenchTestable][AbstractWait] Waiting while shell is available finished successfully

**Comment by odockal** [comment]
Failing test was removed in https://github.com/eclipse/reddeer/issues/1759.
