### ISSUE TITLE
Cannot execute one specific test from IDE

### ISSUE THREAD

**Issue by apodhrad** [eclipse/reddeer#1788]
If you specify a test method in a run configuration in Eclipse IDE then you will get
```
java.lang.Exception: No tests found matching [{ExactMatcher:fDisplayName=testFoo2 fuse-630R4.json], {ExactMatcher:fDisplayName=testFoo2 fuse-630R4.json(org.jboss.tools.fuse.qe.reddeer.tests.FooTest)]] from org.junit.internal.requests.ClassRequest@7847a87f
	at org.junit.internal.requests.FilterRequest.getRunner(FilterRequest.java:40)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createFilteredTest(JUnit4TestLoader.java:77)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:68)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:43)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:444)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.reddeer.eclipse.core.RemotePluginTestRunner.main(RemotePluginTestRunner.java:69)
	at org.eclipse.reddeer.eclipse.core.UITestApplication.runTests(UITestApplication.java:125)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable.lambda$0(E4Testable.java:73)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by apodhrad** [comment]
Laso have a look at #1402

**Comment by odockal** [comment]
I found out that method's name contains not only method name, but also another substring ("default") while being processed via RemoteTestRunner. So the testName (method name) is something like "org.eclipse.reddeer.common.adaptable.RedDeerAdaptableTest:testAdoptBottomClassAToMidClass default", such method does not exist and that the error here. I am going to dig deeper to find out where is the testName derived from.

**Comment by odockal** [comment]
Problem originates here: https://github.com/eclipse/reddeer/blob/02584bf1d10c8922bf616e670a8aeeca8a7b4f23/plugins/org.eclipse.reddeer.ui/src/org/eclipse/reddeer/eclipse/core/RemotePluginTestRunner.java#L103

It adds " default" string to test runner's arguments denoted by -test that contains testClass::testName for which runner searches later and that actually does not exist... That is why "No tests found matching..."
