### ISSUE TITLE
Provide more information if no configuration meets a requirement

### ISSUE THREAD

**Issue by apodhrad** [eclipse/reddeer#1805]
Assume a test with requirement restriction
```
@RequirementRestriction
public static RequirementMatcher getRestrictionMatcher() {
    return new RequirementMatcher(Fuse.class, "server", new ServerTypeMatcher(ServerAS.class));
}
```
and there is no configuration which meets the server type. The followin error occurs
```
org.eclipse.reddeer.junit.internal.runner.TestWithoutExecutionRunner$TestHasNoRunError
	at org.eclipse.reddeer.junit.internal.runner.TestWithoutExecutionRunner.collectInitializationErrors(TestWithoutExecutionRunner.java:59)
	at org.junit.runners.ParentRunner.validate(ParentRunner.java:416)
	at org.junit.runners.ParentRunner.<init>(ParentRunner.java:84)
	at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:65)
	at org.eclipse.reddeer.junit.internal.runner.TestWithoutExecutionRunner.<init>(TestWithoutExecutionRunner.java:42)
	at org.eclipse.reddeer.junit.internal.runner.TestsWithoutExecutionSuite$TestsWithoutRunRunnerBuilder.runnerForClass(TestsWithoutExecutionSuite.java:88)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:101)
	at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:87)
	at org.junit.runners.Suite.<init>(Suite.java:102)
	at org.eclipse.reddeer.junit.internal.runner.TestsWithoutExecutionSuite.<init>(TestsWithoutExecutionSuite.java:54)
	at org.eclipse.reddeer.junit.runner.RedDeerSuite.createSuites(RedDeerSuite.java:121)
	at org.eclipse.reddeer.junit.runner.RedDeerSuite.<init>(RedDeerSuite.java:94)
	at org.eclipse.reddeer.junit.runner.RedDeerSuite.<init>(RedDeerSuite.java:76)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:107)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createUnfilteredTest(JUnit4TestLoader.java:84)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:70)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:43)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:444)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.reddeer.eclipse.core.RemotePluginTestRunner.main(RemotePluginTestRunner.java:69)
	at org.eclipse.reddeer.eclipse.core.UITestApplication.runTests(UITestApplication.java:125)
	at org.eclipse.e4.ui.internal.workbench.swt.E4Testable.lambda$0(E4Testable.java:73)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by apodhrad** [comment]
Some message would be nice ;-)
