### ISSUE TITLE
Failing test JavaEditorTest.testRemovingBreakpoint 

### ISSUE THREAD

**Issue by rawagner** [eclipse/reddeer#1825]
https://hudson.eclipse.org/reddeer/job/reddeer.prcheck/173/testReport/junit/org.eclipse.reddeer.eclipse.test.jdt.ui.javaeditor/JavaEditorTest/testRemovingBreakpoint_no_configuration/

```
java.lang.NullPointerException
	at org.eclipse.reddeer.eclipse.jdt.ui.javaeditor.JavaEditor.getBreakpointLabel(JavaEditor.java:136)
	at org.eclipse.reddeer.eclipse.jdt.ui.javaeditor.JavaEditor.getBreakpoints(JavaEditor.java:121)
	at org.eclipse.reddeer.eclipse.jdt.ui.javaeditor.JavaEditor.addBreakpoint(JavaEditor.java:78)
	at org.eclipse.reddeer.eclipse.test.jdt.ui.javaeditor.JavaEditorTest.testRemovingBreakpoint(JavaEditorTest.java:102)
```

**Comment by odockal** [comment]
Out of date.
