### ISSUE TITLE
Reset perspective fails with Eclipse Platform 4.8 I-builds

### ISSUE THREAD

**Issue by akurtakov** [eclipse/reddeer#1880]
Bug 530312 in eclipse bz but creating it here in case devs look here.
 If reddeer test is run when using Eclipse 4.8. The following error happens:
class org.eclipse.swt.widgets.Shell[shell: 'Reset Perspective'] with text 'Reset Perspective'
	class org.eclipse.swt.widgets.Label[shell: 'Reset Perspective'] with text ''
	class org.eclipse.swt.widgets.Label[shell: 'Reset Perspective'] with text 'Do you want to reset the current Docker Tooling perspective to its defaults?'
	class org.eclipse.swt.widgets.Composite[shell: 'Reset Perspective'] with label 'Do you want to reset the current Docker Tooling perspective to its defaults?'
		class org.eclipse.swt.widgets.Label[shell: 'Reset Perspective'] with label 'Do you want to reset the current Docker Tooling perspective to its defaults?' with text ''
	class org.eclipse.swt.widgets.Composite[shell: 'Reset Perspective'] with label ''
		class org.eclipse.swt.widgets.Button[shell: 'Reset Perspective'] with label '' with text '&No'
		class org.eclipse.swt.widgets.Button[shell: 'Reset Perspective'] with label '' with text '&Reset Perspective'

	at org.eclipse.reddeer.core.lookup.WidgetLookup.activeWidget(WidgetLookup.java:112)
	at org.eclipse.reddeer.core.lookup.WidgetLookup.activeWidget(WidgetLookup.java:85)
	at org.eclipse.reddeer.swt.widgets.AbstractWidget.<init>(AbstractWidget.java:75)
	at org.eclipse.reddeer.swt.widgets.AbstractControl.<init>(AbstractControl.java:34)
	at org.eclipse.reddeer.swt.impl.button.AbstractButton.<init>(AbstractButton.java:42)
	at org.eclipse.reddeer.swt.impl.button.PredefinedButton.<init>(PredefinedButton.java:28)
	at org.eclipse.reddeer.swt.impl.button.YesButton.<init>(YesButton.java:47)
	at org.eclipse.reddeer.swt.impl.button.YesButton.<init>(YesButton.java:37)
	at org.eclipse.reddeer.swt.impl.button.YesButton.<init>(YesButton.java:28)
	at org.eclipse.reddeer.eclipse.ui.perspectives.AbstractPerspective.reset(AbstractPerspective.java:123)
	at org.eclipse.reddeer.requirements.openperspective.OpenPerspectiveRequirement.fulfill(OpenPerspectiveRequirement.java:83)
	at org.eclipse.reddeer.junit.internal.requirement.Requirements.runSafely(Requirements.java:109)
	at org.eclipse.reddeer.junit.internal.requirement.Requirements.lambda$0(Requirements.java:104)
	at java.util.ArrayList.forEach(ArrayList.java:1257)

**Comment by odockal** [comment]
Was resolved in referenced PR. Thanks @akurtakov. Closing.
