### ISSUE TITLE
NPE when (new ProjectExplorer()).getProjects()

### ISSUE THREAD

**Issue by zcervink** [eclipse/reddeer#2005]

**Comment by ruspl-afed** [comment]
It fails also during Eclipse PDE UI Tests
Example of stack trace
```
java.lang.NullPointerException
	at org.eclipse.reddeer.eclipse.ui.navigator.resources.AbstractExplorer.getExplorerTreeItems(AbstractExplorer.java:234)
	at org.eclipse.reddeer.eclipse.ui.navigator.resources.AbstractExplorer.getProjects(AbstractExplorer.java:114)
	at org.eclipse.ui.tests.smartimport.ProjectTestTemplate.cleanup(ProjectTestTemplate.java:65)
```
