### ISSUE TITLE
The embedded browser widget for this editor cannot be created. It is either not available for your operating system or the system needs to be configured in order to support embedded browser

### ISSUE THREAD

**Issue by odockal** [eclipse/reddeer#2059]
```
The embedded browser widget for this editor cannot be created. It is either not available for your operating system or the system needs to be configured in order to support embedded browser.' with text 'No more handles because there is no underlying browser available.
Please ensure that WebKit with its GTK 3.x bindings is installed (WebKit2 API level is preferred). Additionally, please note that GTK4 does not currently have Browser support.
```

And stacktrace:
```
org.eclipse.swt.SWTError: No more handles because there is no underlying browser available.
Please ensure that WebKit with its GTK 3.x bindings is installed (WebKit2 API level is preferred). Additionally, please note that GTK4 does not currently have Browser support.

 at org.eclipse.swt.SWT.error(SWT.java:4749)
 at org.eclipse.swt.browser.Browser.<init>(Browser.java:123)
 at org.eclipse.ui.internal.browser.BrowserViewer.<init>(BrowserViewer.java:235)
 at org.eclipse.ui.internal.browser.WebBrowserView.createPartControl(WebBrowserView.java:51)
 at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.createPartControl(CompatibilityPart.java:154)
 at org.eclipse.ui.internal.e4.compatibility.CompatibilityView.createPartControl(CompatibilityView.java:155)
 at org.eclipse.ui.internal.e4.compatibility.CompatibilityPart.create(CompatibilityPart.java:361)
 at sun.reflect.GeneratedMethodAccessor68.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
 at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:1002)
 at org.eclipse.e4.core.internal.di.InjectorImpl.processAnnotated(InjectorImpl.java:967)
 at org.eclipse.e4.core.internal.di.InjectorImpl.internalInject(InjectorImpl.java:139)
 at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:408)
 at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:331)
 at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:202)
 at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.createFromBundle(ReflectionContributionFactory.java:91)
 at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.doCreate(ReflectionContributionFactory.java:60)
 at org.eclipse.e4.ui.internal.workbench.ReflectionContributionFactory.create(ReflectionContributionFactory.java:42)
 at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer.createWidget(ContributedPartRenderer.java:132)
 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:1002)
 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:662)
 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$1.run(PartRenderingEngine.java:547)
 at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:531)
 at org.eclipse.e4.ui.workbench.renderers.swt.ElementReferenceRenderer.createWidget(ElementReferenceRenderer.java:73)
 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createWidget(PartRenderingEngine.java:1002)
 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:662)
 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.safeCreateGui(PartRenderingEngine.java:768)
 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.access$0(PartRenderingEngine.java:739)
 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$2.run(PartRenderingEngine.java:733)
 at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.createGui(PartRenderingEngine.java:717)
 at org.eclipse.e4.ui.internal.workbench.PartServiceImpl$1.handleEvent(PartServiceImpl.java:112)
 at org.eclipse.e4.ui.services.internal.events.UIEventHandler.lambda$0(UIEventHandler.java:38)
 at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:236)
 at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
 at org.eclipse.swt.widgets.Display.syncExec(Display.java:5797)
 at org.eclipse.e4.ui.internal.workbench.swt.E4Application$1.syncExec(E4Application.java:219)
 at org.eclipse.e4.ui.services.internal.events.UIEventHandler.handleEvent(UIEventHandler.java:38)
 at org.eclipse.equinox.internal.event.EventHandlerWrapper.handleEvent(EventHandlerWrapper.java:205)
 at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:203)
 at org.eclipse.equinox.internal.event.EventHandlerTracker.dispatchEvent(EventHandlerTracker.java:1)
 at org.eclipse.osgi.framework.eventmgr.EventManager.dispatchEvent(EventManager.java:234)
 at org.eclipse.osgi.framework.eventmgr.ListenerQueue.dispatchEventSynchronous(ListenerQueue.java:151)
 at org.eclipse.equinox.internal.event.EventAdminImpl.dispatchEvent(EventAdminImpl.java:132)
 at org.eclipse.equinox.internal.event.EventAdminImpl.sendEvent(EventAdminImpl.java:75)
 at org.eclipse.equinox.internal.event.EventComponent.sendEvent(EventComponent.java:44)
 at org.eclipse.e4.ui.services.internal.events.EventBroker.send(EventBroker.java:55)
 at org.eclipse.e4.ui.internal.workbench.UIEventPublisher.notifyChanged(UIEventPublisher.java:63)
 at org.eclipse.emf.common.notify.impl.BasicNotifierImpl.eNotify(BasicNotifierImpl.java:424)
 at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElementGen(ElementContainerImpl.java:170)
 at org.eclipse.e4.ui.model.application.ui.impl.ElementContainerImpl.setSelectedElement(ElementContainerImpl.java:188)
 at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.showElementInWindow(ModelServiceImpl.java:661)
 at org.eclipse.e4.ui.internal.workbench.ModelServiceImpl.bringToTop(ModelServiceImpl.java:625)
 at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.delegateBringToTop(PartServiceImpl.java:790)
 at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:761)
 at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:683)
 at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:678)
 at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.showPart(PartServiceImpl.java:1257)
 at org.eclipse.ui.internal.WorkbenchPage.showPart(WorkbenchPage.java:1249)
 at org.eclipse.ui.internal.WorkbenchPage.busyShowView(WorkbenchPage.java:1237)
 at org.eclipse.ui.internal.WorkbenchPage.lambda$11(WorkbenchPage.java:4249)
 at org.eclipse.swt.custom.BusyIndicator.showWhile(BusyIndicator.java:72)
 at org.eclipse.ui.internal.WorkbenchPage.showView(WorkbenchPage.java:4247)
 at org.eclipse.ui.internal.WorkbenchPage.showView(WorkbenchPage.java:4229)
 at org.eclipse.ui.handlers.ShowViewHandler.openView(ShowViewHandler.java:135)
 at org.eclipse.ui.handlers.ShowViewHandler.openOther(ShowViewHandler.java:114)
 at org.eclipse.ui.handlers.ShowViewHandler.execute(ShowViewHandler.java:81)
 at org.eclipse.ui.internal.handlers.HandlerProxy.execute(HandlerProxy.java:283)
 at org.eclipse.ui.internal.handlers.E4HandlerProxy.execute(E4HandlerProxy.java:97)
 at sun.reflect.GeneratedMethodAccessor67.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at org.eclipse.e4.core.internal.di.MethodRequestor.execute(MethodRequestor.java:58)
 at org.eclipse.e4.core.internal.di.InjectorImpl.invokeUsingClass(InjectorImpl.java:318)
 at org.eclipse.e4.core.internal.di.InjectorImpl.invoke(InjectorImpl.java:252)
 at org.eclipse.e4.core.contexts.ContextInjectionFactory.invoke(ContextInjectionFactory.java:173)
 at org.eclipse.e4.core.commands.internal.HandlerServiceHandler.execute(HandlerServiceHandler.java:156)
 at org.eclipse.core.commands.Command.executeWithChecks(Command.java:488)
 at org.eclipse.core.commands.ParameterizedCommand.executeWithChecks(ParameterizedCommand.java:487)
 at org.eclipse.e4.core.commands.internal.HandlerServiceImpl.executeHandler(HandlerServiceImpl.java:213)
 at org.eclipse.ui.internal.handlers.LegacyHandlerService.executeCommand(LegacyHandlerService.java:389)
 at org.eclipse.ui.internal.ShowViewMenu$1.run(ShowViewMenu.java:135)
 at org.eclipse.jface.action.Action.runWithEvent(Action.java:474)
 at org.eclipse.jface.action.ActionContributionItem.handleWidgetSelection(ActionContributionItem.java:579)
 at org.eclipse.jface.action.ActionContributionItem.lambda$4(ActionContributionItem.java:413)
 at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
 at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5687)
 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1423)
 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1449)
 at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1432)
 at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1221)
 at org.eclipse.reddeer.core.handler.MenuItemHandler$4.run(MenuItemHandler.java:109)
 at org.eclipse.reddeer.common.util.Display$VoidResultRunnable.run(Display.java:196)
 at org.eclipse.reddeer.common.util.Display$VoidResultRunnable.run(Display.java:1)
 at org.eclipse.reddeer.common.util.Display$ErrorHandlingRunnable.run(Display.java:162)
 at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:40)
 at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:185)
 at org.eclipse.swt.widgets.Display.runAsyncMessages(Display.java:4930)
 at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4451)
 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$5.run(PartRenderingEngine.java:1160)
 at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
 at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1049)
 at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:155)
 at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:658)
 at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:338)
 at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:557)
 at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:154)
 at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:150)
 at org.eclipse.tycho.surefire.osgibooter.UITestApplication.runApplication(UITestApplication.java:31)
 at org.eclipse.tycho.surefire.osgibooter.AbstractUITestApplication.run(AbstractUITestApplication.java:120)
 at org.eclipse.tycho.surefire.osgibooter.UITestApplication.start(UITestApplication.java:37)
 at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:203)
 at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:137)
 at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:107)
 at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:401)
 at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:255)
 at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 at java.lang.reflect.Method.invoke(Method.java:498)
 at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:657)
 at org.eclipse.equinox.launcher.Main.basicRun(Main.java:594)
 at org.eclipse.equinox.launcher.Main.run(Main.java:1447)
 at org.eclipse.equinox.launcher.Main.main(Main.java:1420)
```

**Comment by odockal** [comment]
Upstream issue: https://bugs.eclipse.org/bugs/show_bug.cgi?id=560457

**Comment by odockal** [comment]
Request for webkit2gtk3 package addition into migration-fat-agent image.

**Comment by odockal** [comment]
seems to be solve in https://bugs.eclipse.org/bugs/show_bug.cgi?id=562762 request. Eclipse/RedDeer CI was upgraded and new image with webkitgtk4 was used - tests fail no more.
